version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80" # Serve frontend via port 80
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "5002:5000"
    environment:
      DATABASE_URL: postgresql://user:password@database:5432/qrdb
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: postgres_prod
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qrdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
